#!/usr/bin/env node
/**
 * Reporter Agent
 *
 * Reads the evaluation and formats a human-readable report.
 * Optionally posts a summary comment to ClickUp tasks.
 *
 * Input:  tasks/running/<plan>.json (with evaluation set)
 * Output: reports/<plan-id>-report.md, moves plan to tasks/completed/
 */

import 'dotenv/config';
import axios from 'axios';
import { readFileSync, writeFileSync, renameSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..', '..');

const CLICKUP_TOKEN = process.env.CLICKUP_API_TOKEN;

export async function report(planFile) {
  const runningPath = join(ROOT, 'tasks', 'running', planFile);

  if (!existsSync(runningPath)) {
    throw new Error(`Plan not found in running: ${runningPath}`);
  }

  const plan = JSON.parse(readFileSync(runningPath, 'utf8'));

  if (!plan.evaluation) {
    throw new Error('Plan has no evaluation — run the evaluator first');
  }

  const { evaluation } = plan;
  const icon = evaluation.verdict === 'PASS' ? '✅'
    : evaluation.verdict === 'PASS_WITH_WARNINGS' ? '⚠️'
    : evaluation.verdict === 'FAIL' ? '⚠️' : '🚨';
  const recommendation = evaluation.verdict === 'BLOCKED'
    ? 'Do not merge. Critical failures detected.'
    : evaluation.verdict === 'FAIL'
      ? 'Some tests failed. Review before merging.'
      : evaluation.verdict === 'PASS_WITH_WARNINGS'
        ? 'Tests passed but extraction completeness has gaps. Review missing fields before merging.'
        : 'All tests passed. Safe to proceed.';
  const timestamp = new Date().toISOString().replace('T', ' ').slice(0, 16) + ' UTC';

  const testType = evaluation.testType || plan.testType || 'full-regression';
  const skippedSuites = evaluation.skippedSuites || [];
  const documentCategory  = plan.documentCategory  || null;
  const parseFileType     = plan.parseFileType     || null;
  const batchDocumentType = plan.batchDocumentType || null;
  const selectedTestReason = plan.selectedTestReason || null;
  const selectedFixtures  = plan.selectedFixtures  || [];
  const fixtureSource     = plan.fixtureSource     || null;
  const selectedFolder    = plan.selectedFolder    || null;
  const validationFocus     = plan.validationFocus     || null;
  const affectedFields      = plan.affectedFields      || [];
  const testRationale       = plan.testRationale       || null;
  const fixtureRequirements = plan.fixtureRequirements || [];
  const mappingProfile      = plan.mappingProfile      || null;
  const mappingConfidence   = plan.mappingConfidence   || null;

  // Which doc type field is relevant for this test run
  const activeDocType = testType === 'batch-upload' ? batchDocumentType : parseFileType;

  // Build markdown report
  let md;

  if (testType === 'auth-boundary') {
    // Auth-boundary: show auth results only, no API test summary sections
    const authResults = evaluation.authBoundary?.results || [];
    const authRows = authResults.map(r => {
      const rIcon = r.passed ? '✅' : '❌';
      return `| \`${r.id}\` | ${rIcon} | ${r.message} |`;
    }).join('\n');

    md = [
      `## QA Result: ${evaluation.verdict} ${icon}`,
      '',
      `> ${recommendation}`,
      '',
      `**Test type:** Auth Boundary Tests Only`,
      `**Pass rate:** ${evaluation.passRate} (${evaluation.passed}/${evaluation.total})`,
      `**Duration:** ${(evaluation.durationMs / 1000).toFixed(1)}s`,
      `**Preview URL:** ${plan.previewUrl}`,
      `**Evaluated at:** ${timestamp}`,
      documentCategory  ? `**Document category:** ${documentCategory}` : null,
      activeDocType     ? `**Document type (${testType === 'batch-upload' ? 'batchDocumentType' : 'parseFileType'}):** ${activeDocType}` : null,
      selectedTestReason ? `**Selection reason:** ${selectedTestReason}` : null,
      mappingProfile    ? `**Mapping profile:** ${mappingProfile} (${mappingConfidence === 'generic' ? '⚠️ generic — no learned mapping' : '✅ learned'})` : null,
      '',
      '### Auth Boundary Results',
      '',
      '| Test ID | Result | Message |',
      '|---------|--------|---------|',
      authRows,
      '',
      '---',
      'Generated by verifyiq-qa-automation pipeline',
    ].join('\n');
  } else {
    const skippedLine = skippedSuites.length
      ? `**Skipped suites (not run):** ${skippedSuites.join(', ')}`
      : null;

    // Fixture table — use requirement-aware columns when annotations exist
    const hasReqAnnotations = selectedFixtures.some(f => f.matchedRequirement !== undefined);
    const fixtureTableHeader = hasReqAnnotations
      ? '| Fixture | fileType | requirement | confidence | file |'
      : '| Fixture | fileType | source | file |';
    const fixtureTableSeparator = hasReqAnnotations
      ? '|---------|----------|-------------|------------|------|'
      : '|---------|----------|--------|------|';
    const fixtureTableRows = selectedFixtures.map(f =>
      hasReqAnnotations
        ? `| \`${f.fixtureKey}\` | \`${f.fileType}\` | ${f.matchedRequirement ? `*${f.matchedRequirement}*` : '—'} | ${f.lowConfidence ? '⚠️ low' : '✅'} | \`${f.file}\` |`
        : `| \`${f.fixtureKey}\` | \`${f.fileType}\` | ${f.source ?? '—'} | \`${f.file}\` |`
    );
    const requirementLines = fixtureRequirements.map(req => {
      const match = selectedFixtures.find(f => f.matchedRequirement === req);
      if (!match) return `- ❌ **${req}** — no fixture found`;
      if (match.lowConfidence) return `- ⚠️ **${req}** — \`${match.fixtureKey}\` *(low confidence — no exact match)*`;
      return `- ✅ **${req}** — \`${match.fixtureKey}\``;
    });

    // Parse assertions — all parse cases share the same assertion set; grab from first annotated fixture
    const parseAssertions = selectedFixtures.find(f => Array.isArray(f.assertions))?.assertions ?? [];
    const strongCount = parseAssertions.filter(a => a.strength === 'strong').length;
    const assertionRows = parseAssertions.map(a => {
      let typeCol, validatesCol, strengthIcon;
      if (a.assertionType === 'computed') {
        typeCol      = 'computed';
        validatesCol = a.description;
        strengthIcon = '🔢 computed';
      } else if (a.assertionType === 'completenessScore') {
        typeCol      = 'score';
        validatesCol = `≥${a.thresholds?.pass ?? 90}/${a.maxScore ?? 100}`;
        strengthIcon = '📊 scoring';
      } else if (a.assertionType === 'type') {
        typeCol      = 'type';
        validatesCol = a.expectedType;
        strengthIcon = a.strength === 'strong' ? '✅ strong' : '⚠️ weak';
      } else if (a.assertionType === 'pattern') {
        typeCol      = 'pattern';
        validatesCol = `\`${a.pattern}\``;
        strengthIcon = a.strength === 'strong' ? '✅ strong' : '⚠️ weak';
      } else {
        typeCol      = 'exists';
        validatesCol = `\`${a.pattern ?? '.+'}\``;
        strengthIcon = a.strength === 'strong' ? '✅ strong' : '⚠️ weak';
      }
      const pathCol = a.assertionType === 'computed'
        ? `computed:${a.check}`
        : a.assertionType === 'completenessScore'
          ? 'completenessScore'
          : a.path;
      return `| \`${pathCol}\` | ${typeCol} | ${validatesCol} | ${strengthIcon} | ${a.description} |`;
    });

    // Completeness scores extracted by the runner from [completeness] output lines
    const completenessResults = plan.runResult?.completenessResults || [];
    const completenessRows = completenessResults.map(cr => {
      const sIcon = cr.status === 'PASS' ? '✅' : cr.status === 'WARN' ? '⚠️' : '❌';
      const reqMissing = cr.missingRequired.length ? cr.missingRequired.join(', ') : '—';
      const optMissing = cr.missingOptional.length ? cr.missingOptional.join(', ') : '—';
      return `| \`${cr.tcId}\` | ${cr.score}/${cr.maxScore} | ${sIcon} ${cr.status} | ${reqMissing} | ${optMissing} |`;
    });

    md = [
      `## QA Result: ${evaluation.verdict} ${icon}`,
      '',
      `> ${recommendation}`,
      '',
      `**Test type:** ${testType}`,
      `**Pass rate:** ${evaluation.passRate} (${evaluation.passed}/${evaluation.total})`,
      `**Duration:** ${(evaluation.durationMs / 1000).toFixed(1)}s`,
      `**Preview URL:** ${plan.previewUrl}`,
      `**Evaluated at:** ${timestamp}`,
      documentCategory  ? `**Document category:** ${documentCategory}` : null,
      activeDocType     ? `**Document type (${testType === 'batch-upload' ? 'batchDocumentType' : 'parseFileType'}):** ${activeDocType}` : null,
      selectedTestReason ? `**Selection reason:** ${selectedTestReason}` : null,
      mappingProfile    ? `**Mapping profile:** ${mappingProfile} (${mappingConfidence === 'generic' ? '⚠️ generic — no learned mapping' : '✅ learned'})` : null,
      testRationale     ? `**Scope rationale:** ${testRationale}` : null,
      validationFocus   ? `**Validation focus:** ${validationFocus}` : null,
      affectedFields.length ? `**Affected fields:** \`${affectedFields.join('`, `')}\`` : null,
      skippedLine,
      '',
      '### Summary',
      '',
      `| Metric | Value |`,
      `|--------|-------|`,
      `| Test type | ${testType} |`,
      documentCategory  ? `| Document category | ${documentCategory} |` : null,
      activeDocType     ? `| ${testType === 'batch-upload' ? 'batchDocumentType' : 'parseFileType'} | ${activeDocType} |` : null,
      mappingProfile    ? `| Mapping profile | ${mappingProfile} (${mappingConfidence}) |` : null,
      validationFocus   ? `| Validation focus | ${validationFocus} |` : null,
      affectedFields.length ? `| Affected fields | \`${affectedFields.join('`, `')}\` |` : null,
      `| Total tests | ${evaluation.total} |`,
      `| Passed | ${evaluation.passed} |`,
      `| Failed | ${evaluation.failed} |`,
      `| Exit code | ${evaluation.exitCode} |`,
      skippedSuites.length ? `| Skipped suites | ${skippedSuites.join(', ')} (not run) |` : null,
      selectedFixtures.length ? '' : null,
      selectedFixtures.length ? '### Fixtures used' : null,
      selectedFixtures.length && (fixtureSource || selectedFolder)
        ? `**Source:** ${fixtureSource === 'gcs' ? `GCS \`gs://test-ai-docs-data-dev/qa-test-data/${selectedFolder}/\`` : 'fixture-registry.json'}`
        : null,
      selectedFixtures.length ? '' : null,
      selectedFixtures.length ? fixtureTableHeader : null,
      selectedFixtures.length ? fixtureTableSeparator : null,
      ...fixtureTableRows,
      fixtureRequirements.length ? '' : null,
      fixtureRequirements.length ? '### Fixture requirements' : null,
      fixtureRequirements.length ? '' : null,
      ...requirementLines,
      parseAssertions.length ? '' : null,
      parseAssertions.length ? `### Assertions per parse case (${parseAssertions.length} total — ${strongCount} strong, ${parseAssertions.length - strongCount} weak)` : null,
      parseAssertions.length ? '' : null,
      parseAssertions.length ? '| Path | Type | Validates | Strength | Description |' : null,
      parseAssertions.length ? '|------|------|-----------|----------|-------------|' : null,
      ...assertionRows,
      completenessResults.length ? '' : null,
      completenessResults.length ? '### Completeness Scores' : null,
      completenessResults.length ? '' : null,
      (() => {
        if (!completenessResults.length) return null;
        const c = evaluation.completeness;
        if (!c) return `> Weighted field-presence score per fixture. PASS ≥ 90, WARN ≥ 70, FAIL < 70.`;
        const cvIcon = c.completenessVerdict === 'PASS' ? '✅' : c.completenessVerdict === 'PASS_WITH_WARNINGS' ? '⚠️' : '❌';
        const parts = [`${cvIcon} **${c.completenessVerdict}**`, `Avg: ${c.avgScore}`, `Lowest: ${c.lowestScore}`];
        if (c.warnCount) parts.push(`WARN: ${c.warnCount}`);
        if (c.failCount) parts.push(`FAIL: ${c.failCount}`);
        return `> ${parts.join(' · ')}`;
      })(),
      completenessResults.length ? '' : null,
      completenessResults.length ? '| Fixture | Score | Status | Missing Required | Missing Optional |' : null,
      completenessResults.length ? '|---------|-------|--------|-----------------|-----------------|' : null,
      ...completenessRows,
      '',
      `---`,
      `Generated by verifyiq-qa-automation pipeline`,
    ].filter(line => line !== null).join('\n');
  }

  const reportFile = `${plan.id}-report.md`;
  const reportPath = join(ROOT, 'reports', reportFile);
  writeFileSync(reportPath, md);

  console.log(`[reporter] Report written: reports/${reportFile}`);

  // Post to ClickUp tasks if configured and not disabled
  const disableClickUp = plan.disableClickUp || plan.disableRemote
    || process.env.DISABLE_CLICKUP === 'true'
    || process.env.DISABLE_REMOTE_POSTING === 'true';
  if (disableClickUp) {
    console.log('[reporter] ClickUp disabled — skipping remote updates');
  }
  if (CLICKUP_TOKEN && plan.clickupTaskIds?.length && !disableClickUp) {
    const clickup = axios.create({
      baseURL: 'https://api.clickup.com/api/v2',
      headers: { Authorization: CLICKUP_TOKEN },
    });

    for (const taskId of plan.clickupTaskIds) {
      try {
        const docTypeLine = activeDocType
          ? `${testType === 'batch-upload' ? 'batchDocumentType' : 'parseFileType'}: ${activeDocType}${documentCategory ? ` (${documentCategory})` : ''}`
          : null;
        const commentLines = testType === 'auth-boundary'
          ? [
              `${icon} QA Result: ${evaluation.verdict} — PR #${plan.prNumber}`,
              '',
              `> ${recommendation}`,
              '',
              `Test type: Auth Boundary Tests Only`,
              `Pass rate: ${evaluation.passRate} (${evaluation.passed}/${evaluation.total})`,
              `Duration: ${(evaluation.durationMs / 1000).toFixed(1)}s`,
              docTypeLine,
              '',
              `Ran at ${timestamp}`,
            ]
          : [
              `${icon} QA Result: ${evaluation.verdict} — PR #${plan.prNumber}`,
              '',
              `> ${recommendation}`,
              '',
              `Test type: ${testType}`,
              `Pass rate: ${evaluation.passRate} (${evaluation.passed}/${evaluation.total})`,
              `Duration: ${(evaluation.durationMs / 1000).toFixed(1)}s`,
              docTypeLine,
              mappingProfile
                ? `Mapping: ${mappingProfile} (${mappingConfidence})`
                : null,
              validationFocus && affectedFields.length
                ? `Validation focus: ${validationFocus} — ${affectedFields.join(', ')}`
                : null,
              (() => {
                const unmet = fixtureRequirements.filter(req => {
                  const match = selectedFixtures.find(f => f.matchedRequirement === req);
                  return !match || match.lowConfidence;
                });
                return unmet.length
                  ? `⚠️ Low-confidence fixtures for: ${unmet.join(', ')}`
                  : null;
              })(),
              skippedSuites.length ? `Skipped suites (not run): ${skippedSuites.join(', ')}` : null,
              selectedFixtures.length
                ? `Fixtures (${fixtureSource ?? 'unknown source'}): ${selectedFixtures.map(f => f.fixtureKey).join(', ')}`
                : null,
              (() => {
                if (!completenessResults.length) return null;
                const c = evaluation.completeness;
                if (c && c.completenessVerdict !== 'PASS') {
                  const parts = [`Completeness: ${c.completenessVerdict}`, `avg=${c.avgScore}`, `lowest=${c.lowestScore}`];
                  if (c.warnCount) parts.push(`warn=${c.warnCount}`);
                  if (c.failCount) parts.push(`fail=${c.failCount}`);
                  if (c.worstCase?.missingRequired?.length) {
                    parts.push(`missing=${c.worstCase.missingRequired.join(',')}`);
                  }
                  return parts.join(' ');
                }
                return `Completeness: ${completenessResults.map(cr => `${cr.tcId}=${cr.score}/${cr.maxScore}(${cr.status})`).join(', ')}`;
              })(),
              '',
              `Ran at ${timestamp}`,
            ];
        await clickup.post(`/task/${taskId}/comment`, {
          comment_text: commentLines.filter(Boolean).join('\n'),
          notify_all: false,
        });
        console.log(`[reporter] Posted result to ClickUp task ${taskId}`);
      } catch (err) {
        console.warn(`[reporter] Could not post to ClickUp ${taskId}: ${err.message}`);
      }
    }
  }

  // Move plan to completed
  plan.status = 'completed';
  plan.reportFile = reportFile;
  plan.completedAt = new Date().toISOString();
  const completedPath = join(ROOT, 'tasks', 'completed', planFile);
  writeFileSync(completedPath, JSON.stringify(plan, null, 2));

  // Remove from running (write completed first to avoid data loss)
  try {
    const { unlinkSync } = await import('fs');
    unlinkSync(runningPath);
  } catch { /* ignore */ }

  console.log(`[reporter] Plan moved to tasks/completed/${planFile}`);
  return { planFile, reportFile, verdict: evaluation.verdict };
}

// CLI entry point
if (process.argv[1] && process.argv[1].includes('reporter')) {
  const planFile = process.argv[2];
  if (!planFile) {
    console.error('Usage: node agents/reporter/index.mjs <plan-file.json>');
    process.exit(1);
  }
  report(planFile).catch(err => {
    console.error(`[reporter] Fatal: ${err.message}`);
    process.exit(1);
  });
}
