#!/usr/bin/env node
/**
 * QA Runner — executes AI-generated test cases against the preview environment.
 *
 * 1. Read test cases from test-cases.json (generated by claude-code-action in qa-on-pr.yml)
 * 2. Create a ClickUp list + tasks for the PR
 * 3. Run each test case as an HTTP call against the preview environment
 * 4. Update each ClickUp task with Actual Result + Status (PASS/FAIL)
 * 5. Post a summary results comment on the PR
 */

import 'dotenv/config';
import axios from 'axios';
import jwt from 'jsonwebtoken';
import { readFileSync } from 'fs';
import { execSync } from 'child_process';

// ── Config ────────────────────────────────────────────────────────────────────

const GITHUB_TOKEN    = process.env.GH_TOKEN;        // VERIFYIQ_PLAYWRIGHT_TOKEN PAT
const PR_REPO         = process.env.PR_REPO;         // owner/repo
const PR_NUMBER       = process.env.PR_NUMBER;
const CLICKUP_TOKEN   = process.env.CLICKUP_API_TOKEN;
const CLICKUP_FOLDER_ID = process.env.CLICKUP_FOLDER_ID || '90147709410';
const VERIFYIQ_KEY    = process.env.VERIFYIQ_API_KEY;
const PREVIEW_URL     = (process.env.VERIFYIQ_SERVICE_URL || '').trim().replace(/\/$/, '');
let   WEBHOOK_TOKEN_ID       = process.env.WEBHOOK_TOKEN_ID; // overwritten at runtime
const WEBHOOK_SERVER_URL     = (process.env.WEBHOOK_SERVER_URL || '').trim().replace(/\/$/, '');
const GOOGLE_SA_KEY_FILE     = process.env.GOOGLE_SA_KEY_FILE;

// ── Webhook server IAP auth ──────────────────────────────────────────────────

let _webhookIapToken = null;

function getWebhookIapToken() {
  if (_webhookIapToken) return _webhookIapToken;
  if (!GOOGLE_SA_KEY_FILE) throw new Error('GOOGLE_SA_KEY_FILE is required for webhook server auth');
  const sa = JSON.parse(readFileSync(GOOGLE_SA_KEY_FILE, 'utf8'));
  const now = Math.floor(Date.now() / 1000);
  _webhookIapToken = jwt.sign(
    {
      iss: sa.client_email,
      sub: sa.client_email,
      aud: WEBHOOK_SERVER_URL,
      iat: now,
      exp: now + 3600,
    },
    sa.private_key,
    { algorithm: 'RS256', keyid: sa.private_key_id },
  );
  console.log(`  ✓ Webhook IAP token generated (${_webhookIapToken.length} chars)`);
  return _webhookIapToken;
}

// ── Webhook token lifecycle ──────────────────────────────────────────────────

async function createWebhookToken() {
  console.log('→ Creating fresh webhook token...');
  const res = await axios.post(`${WEBHOOK_SERVER_URL}/token`, null, {
    headers: { Authorization: `Bearer ${getWebhookIapToken()}` },
    validateStatus: () => true,
  });
  if (res.status !== 201 && res.status !== 200) {
    throw new Error(`Webhook token creation failed: HTTP ${res.status} — ${JSON.stringify(res.data).slice(0, 300)}`);
  }
  const uuid = res.data?.uuid;
  if (!uuid) throw new Error('Webhook server returned no uuid');
  console.log(`  ✓ Webhook token created: ${uuid}`);
  return uuid;
}

async function deleteWebhookToken(uuid) {
  if (!uuid) return;
  console.log(`→ Deleting webhook token ${uuid}...`);
  try {
    await axios.delete(`${WEBHOOK_SERVER_URL}/token/${uuid}`, {
      headers: { Authorization: `Bearer ${getWebhookIapToken()}` },
      validateStatus: () => true,
    });
    console.log('  ✓ Webhook token deleted');
  } catch (err) {
    console.warn(`  ⚠ Could not delete webhook token: ${err.message}`);
  }
}

// ── Startup validation ────────────────────────────────────────────────────────

const REQUIRED_VARS = {
  GH_TOKEN:           GITHUB_TOKEN,
  PR_REPO:            PR_REPO,
  PR_NUMBER:          PR_NUMBER,
  VERIFYIQ_SERVICE_URL: PREVIEW_URL,
};

const missing = Object.entries(REQUIRED_VARS)
  .filter(([, v]) => !v)
  .map(([k]) => k);

if (missing.length) {
  console.error(`Fatal: missing required environment variables: ${missing.join(', ')}`);
  process.exit(1);
}

if (!/^https?:\/\//i.test(PREVIEW_URL)) {
  console.error(`Fatal: VERIFYIQ_SERVICE_URL must start with https:// (got: "${PREVIEW_URL}")`);
  process.exit(1);
}

// ── Axios clients ─────────────────────────────────────────────────────────────

const github = axios.create({
  baseURL: 'https://api.github.com',
  headers: {
    Authorization: `Bearer ${GITHUB_TOKEN}`,
    Accept: 'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28',
  },
});

const clickup = axios.create({
  baseURL: 'https://api.clickup.com/api/v2',
  headers: { Authorization: CLICKUP_TOKEN },
});

// IAP token for /ai-gateway/ and /api/v1/applications/ endpoints (lazy, cached)
let _iapToken = null;
let _iapTokenExp = 0;

function getIapToken() {
  const now = Math.floor(Date.now() / 1000);
  // Return cached token if still valid (with 60s buffer)
  if (_iapToken && now < _iapTokenExp - 60) return _iapToken;

  if (GOOGLE_SA_KEY_FILE) {
    const sa = JSON.parse(readFileSync(GOOGLE_SA_KEY_FILE, 'utf8'));
    const exp = now + 3600;
    _iapToken = jwt.sign(
      {
        iss: sa.client_email,
        sub: sa.client_email,
        aud: PREVIEW_URL,
        iat: now,
        exp,
        target_audience: PREVIEW_URL,
      },
      sa.private_key,
      { algorithm: 'RS256', keyid: sa.private_key_id },
    );
    _iapTokenExp = exp;
    console.log(`  ✓ IAP token generated from service account (aud=${PREVIEW_URL}, ${_iapToken.length} chars)`);
    return _iapToken;
  }

  // Fallback: gcloud CLI
  console.log('→ Generating IAP token via gcloud...');
  _iapToken = execSync('gcloud auth print-identity-token', { encoding: 'utf8' }).trim();
  if (!_iapToken) throw new Error('gcloud auth print-identity-token returned empty');
  _iapTokenExp = now + 3500; // assume ~1h validity
  console.log(`  ✓ IAP token obtained via gcloud (${_iapToken.length} chars)`);
  return _iapToken;
}

function needsIapAuth(endpoint) {
  return endpoint.startsWith('/ai-gateway/') || endpoint.startsWith('/api/v1/applications/');
}

function createPreviewClient(endpoint) {
  const authHeader = needsIapAuth(endpoint)
    ? `Bearer ${getIapToken()}`
    : `Bearer ${VERIFYIQ_KEY}`;
  return axios.create({
    baseURL: PREVIEW_URL,
    headers: {
      Authorization: authHeader,
      'X-Tenant-Token': VERIFYIQ_KEY,
      'Content-Type': 'application/json',
    },
    validateStatus: () => true,
  });
}

// ── Step 1: Load test cases ──────────────────────────────────────────────────

function loadTestCases() {
  console.log('→ Loading test cases from test-cases.json...');
  const raw = readFileSync('test-cases.json', 'utf8');
  const parsed = JSON.parse(raw);

  if (!parsed.test_cases?.length) {
    throw new Error('test-cases.json has no test_cases');
  }

  console.log(`  ✓ ${parsed.test_cases.length} test cases loaded`);
  return parsed;
}

// ── Step 2: Fetch PR metadata ────────────────────────────────────────────────

async function getPr() {
  console.log('→ Fetching PR metadata...');
  const { data } = await github.get(`/repos/${PR_REPO}/pulls/${PR_NUMBER}`);
  return data;
}

// ── Step 3: ClickUp task creation & update ────────────────────────────────────

function buildDescription(tc) {
  const sections = [
    `**${tc.id} — ${tc.title}**`,
    `**Preconditions**\n${tc.preconditions}`,
    `**Steps**\n${tc.steps}`,
    `**Expected Result**\n${tc.expected_result}`,
    `**Endpoint:** ${tc.method} ${tc.endpoint}`,
  ];
  if (tc.payload) {
    sections.push(`**Payload:**\n\`\`\`json\n${JSON.stringify(tc.payload, null, 2)}\n\`\`\``);
  }
  if (tc.payload?.file) {
    sections.push(`**Fixture:** ${tc.payload.file}`);
  } else if (tc.payload?.items?.[0]?.file) {
    sections.push(`**Fixture:** ${tc.payload.items[0].file}`);
  }
  return sections.join('\n\n');
}

// Created at runtime in main() — a new list per PR inside CLICKUP_FOLDER_ID
let clickupListId = null;

async function clearClickUpList() {
  try {
    const { data } = await clickup.get(`/list/${clickupListId}/task`);
    const tasks = data.tasks ?? [];
    if (!tasks.length) return;
    console.log(`  Deleting ${tasks.length} stale tasks from previous run...`);
    for (const task of tasks) {
      await clickup.delete(`/task/${task.id}`);
    }
    console.log(`  ✓ Cleared ${tasks.length} stale tasks`);
  } catch (err) {
    console.warn(`  ⚠ Could not clear stale tasks: ${err.message}`);
  }
}

async function createClickUpList(pr) {
  if (!CLICKUP_TOKEN) {
    console.warn('  ⚠ CLICKUP_API_TOKEN not set — ClickUp integration disabled');
    return;
  }
  const listName = `PR #${PR_NUMBER} - ${pr.title}`;
  try {
    const { data } = await clickup.post(`/folder/${CLICKUP_FOLDER_ID}/list`, {
      name: listName,
    });
    clickupListId = data.id;
    console.log(`  ✓ ClickUp list created: ${listName} (${clickupListId})`);
  } catch (err) {
    // SUBCAT_016: list name already taken — find and reuse the existing one
    const errCode = err.response?.data?.ECODE ?? err.response?.data?.err ?? '';
    if (errCode === 'SUBCAT_016') {
      console.log(`  ⚠ List "${listName}" already exists, looking up existing list...`);
      try {
        const { data: folder } = await clickup.get(`/folder/${CLICKUP_FOLDER_ID}/list`);
        const existing = folder.lists.find(l => l.name === listName);
        if (existing) {
          clickupListId = existing.id;
          console.log(`  ✓ Reusing existing ClickUp list: ${listName} (${clickupListId})`);
          // Delete stale tasks from previous runs
          await clearClickUpList();
          return;
        }
      } catch (lookupErr) {
        console.warn(`  ⚠ Failed to look up existing lists: ${lookupErr.message}`);
      }
    }
    const errBody = err.response?.data ? JSON.stringify(err.response.data) : 'no response body';
    console.warn(`  ⚠ Could not create ClickUp list in folder ${CLICKUP_FOLDER_ID}: ${err.message}`);
    console.warn(`    Status: ${err.response?.status ?? 'N/A'} — Body: ${errBody}`);
  }
}

async function createClickUpTask(tc) {
  if (!clickupListId) return { id: null, url: null };
  try {
    const { data } = await clickup.post(`/list/${clickupListId}/task`, {
      name: `${tc.id} - ${tc.title}`,
      description: buildDescription(tc),
      tags: [tc.type, 'qa-auto'],
      status: 'to do',
    });
    console.log(`  ✓ ClickUp: ${data.url}`);
    return { id: data.id, url: data.url };
  } catch (err) {
    console.warn(`  ⚠ ClickUp create failed for ${tc.id}: ${err.message}`);
    return { id: null, url: null };
  }
}

function isFixtureNotFound(actualResult, responseBody) {
  const text = `${actualResult} ${JSON.stringify(responseBody ?? '')}`.toLowerCase();
  return text.includes('no such object') || text.includes('fixture') ||
    (text.includes('404') && text.includes('storage.googleapis.com'));
}

async function updateClickUpTask(taskId, tc, actualResult, passed, curlCmd, failedAssertions, assertionResults, responseBody) {
  if (!taskId) return;
  try {
    // Detect fixture-not-found: tag as needs-fixture and keep status as "to do"
    const fixtureNotFound = !passed && isFixtureNotFound(actualResult, responseBody);

    if (fixtureNotFound) {
      await clickup.put(`/task/${taskId}`, {
        status: 'to do',
      });
      // Add needs-fixture tag
      try {
        await clickup.post(`/task/${taskId}/tag/needs-fixture`);
      } catch { /* tag may already exist */ }
    } else {
      await clickup.put(`/task/${taskId}`, {
        status: passed ? 'passed' : 'fail',
      });
    }

    // Post test result as a comment on the task activity
    const statusIcon = passed ? '✅' : fixtureNotFound ? '⚠️' : '❌';
    const statusLabel = passed ? 'PASSED' : fixtureNotFound ? 'SKIPPED' : 'FAILED';
    const timestamp = new Date().toISOString().replace('T', ' ').slice(0, 16) + ' UTC';

    // Extract HTTP status code from actualResult
    const httpStatusMatch = actualResult.match(/HTTP (\d+)/);
    const httpStatus = httpStatusMatch ? httpStatusMatch[1] : actualResult;

    const commentLines = [
      `## ${statusIcon} ${tc.id} ${statusLabel}`,
      `**HTTP Status:** ${httpStatus}`,
    ];

    if (fixtureNotFound) {
      commentLines.push('', '⚠️ Fixture not found in GCS bucket — upload required before this TC can run.');
    }

    // Assertion details
    if (assertionResults?.length) {
      commentLines.push('', '**Assertions:**');
      for (const ar of assertionResults) {
        const icon = ar.passed ? '✅' : '❌';
        commentLines.push(`- ${icon} \`${ar.path}\` → expected: \`${ar.expected}\` → actual: \`${ar.actual}\``);
      }
    }

    if (!passed && !fixtureNotFound && failedAssertions) {
      commentLines.push('', `**Failure Details:**`, failedAssertions);
    }

    // Curl command used
    if (curlCmd) {
      commentLines.push('', '**Curl Command:**', '```', curlCmd, '```');
    }

    // Full API response body (truncated to 3000 chars)
    if (responseBody != null) {
      const responseJson = JSON.stringify(responseBody, null, 2);
      const truncated = responseJson.length > 3000
        ? responseJson.slice(0, 3000) + '\n... (truncated)'
        : responseJson;
      commentLines.push('', '**API Response:**', '```json', truncated, '```');
    }

    commentLines.push('', `Ran at ${timestamp}`);

    await clickup.post(`/task/${taskId}/comment`, {
      comment_text: commentLines.join('\n'),
      notify_all: false,
    });
  } catch (err) {
    console.warn(`  ⚠ ClickUp update failed for ${taskId}: ${err.message}`);
  }
}

// ── Step 4: Run test cases ────────────────────────────────────────────────────

function resolvePath(obj, dotPath) {
  const keys = dotPath.split('.');
  let current = obj;
  for (let i = 0; i < keys.length; i++) {
    if (current == null) throw new Error(`null at "${keys[i]}"`);
    const key = keys[i];
    if (key === '*') {
      // Wildcard: iterate array items, resolve remaining path on each, return first non-null
      if (!Array.isArray(current)) throw new Error(`"*" used on non-array at segment ${i}`);
      const remaining = keys.slice(i + 1).join('.');
      if (!remaining) return current[0]; // * at end → first item
      for (const item of current) {
        try {
          const val = resolvePath(item, remaining);
          if (val != null) return val;
        } catch { /* try next item */ }
      }
      throw new Error(`no array item matched remaining path "${remaining}"`);
    }
    current = Array.isArray(current) ? current[Number(key)] : current[key];
  }
  return current;
}

async function runTestCase(tc) {
  console.log(`  Running ${tc.id} (${tc.type}) — ${tc.method} ${tc.endpoint}`);

  // Log equivalent curl for debugging
  const authType = needsIapAuth(tc.endpoint) ? 'IAP' : 'API_KEY';
  const maskedKey = VERIFYIQ_KEY ? `${VERIFYIQ_KEY.slice(0, 3)}***` : '(unset)';
  const curlParts = [
    `curl -X ${tc.method} '${PREVIEW_URL}${tc.endpoint}'`,
    `-H 'Authorization: Bearer <${authType}_TOKEN>'`,
    `-H 'X-Tenant-Token: ${maskedKey}'`,
    `-H 'Content-Type: application/json'`,
  ];
  if (tc.payload) curlParts.push(`-d '${JSON.stringify(tc.payload)}'`);
  const curlCmd = curlParts.join(' \\\n    ');
  console.log(`  curl: ${curlCmd}`);

  let status, body;

  try {
    const client = createPreviewClient(tc.endpoint);
    const res = await client.request({
      method: tc.method,
      url: tc.endpoint,
      data: tc.payload ?? undefined,
    });
    status = res.status;
    body   = res.data;
  } catch (err) {
    return { passed: false, actualResult: `Request error: ${err.message}`, curlCmd, failedAssertions: null, responseBody: null };
  }

  const expectedStatus = tc.expected_status ?? 200;
  const assertionResults = [];

  if (status !== expectedStatus) {
    const snippet = JSON.stringify(body).slice(0, 300);
    assertionResults.push({
      path: 'HTTP status',
      description: `Expected HTTP ${expectedStatus}`,
      expected: String(expectedStatus),
      actual: String(status),
      passed: false,
    });
    return {
      passed: false,
      actualResult: `Expected HTTP ${expectedStatus}, got ${status}. Body: ${snippet}`,
      curlCmd,
      failedAssertions: `Expected status ${expectedStatus} but received ${status}`,
      assertionResults,
      responseBody: body,
    };
  }

  for (const assertion of (tc.assertions ?? [])) {
    let value;
    try {
      value = resolvePath(body, assertion.path);
    } catch {
      assertionResults.push({
        path: assertion.path,
        description: assertion.description,
        expected: assertion.pattern ?? '(exists)',
        actual: '(not found)',
        passed: false,
      });
      return {
        passed: false,
        actualResult: `Field not found: ${assertion.path}`,
        curlCmd,
        failedAssertions: `Path \`${assertion.path}\` not found in response`,
        assertionResults,
        responseBody: body,
      };
    }
    if (assertion.pattern) {
      // Strip (?i) inline flag (not supported in JS) and use 'i' flag instead
      const hasInlineIgnoreCase = assertion.pattern.includes('(?i)');
      const cleanPattern = assertion.pattern.replace(/\(\?i\)/g, '');
      const flags = hasInlineIgnoreCase ? 'i' : '';
      const matched = new RegExp(cleanPattern, flags).test(String(value));
      assertionResults.push({
        path: assertion.path,
        description: assertion.description,
        expected: assertion.pattern,
        actual: String(value),
        passed: matched,
      });
      if (!matched) {
        return {
          passed: false,
          actualResult: `\`${assertion.path}\` = ${JSON.stringify(value)} did not match \`${assertion.pattern}\``,
          curlCmd,
          failedAssertions: `Assertion: \`${assertion.description}\`\nPath: \`${assertion.path}\`\nActual: ${JSON.stringify(value)}\nExpected pattern: \`${assertion.pattern}\``,
          assertionResults,
          responseBody: body,
        };
      }
    } else {
      assertionResults.push({
        path: assertion.path,
        description: assertion.description,
        expected: '(exists)',
        actual: String(value),
        passed: true,
      });
    }
  }

  return { passed: true, actualResult: `HTTP ${status} — all assertions passed`, curlCmd, failedAssertions: null, assertionResults, responseBody: body };
}

// ── Step 4b: Run batch test cases ────────────────────────────────────────────

const DECRYPT_URL = process.env.DECRYPT_URL || 'https://us-central1-boost-capital-staging.cloudfunctions.net/verifyiq-gateway/utils/decrypt';

function sleep(ms) { return new Promise(r => setTimeout(r, ms)); }

async function getWebhookBaseline() {
  const res = await axios.get(
    `${WEBHOOK_SERVER_URL}/token/${WEBHOOK_TOKEN_ID}/requests?per_page=50`,
    { headers: { Authorization: `Bearer ${getWebhookIapToken()}` }, validateStatus: () => true }
  );
  return res.data?.data?.length ?? 0;
}

async function pollWebhookCallbacks(baselineCount, expectedCount, applicationId, timeoutMs = 90_000) {
  const start = Date.now();
  while (Date.now() - start < timeoutMs) {
    await sleep(3_000);
    const res = await axios.get(
      `${WEBHOOK_SERVER_URL}/token/${WEBHOOK_TOKEN_ID}/requests?per_page=50`,
      { headers: { Authorization: `Bearer ${getWebhookIapToken()}` }, validateStatus: () => true }
    );
    const all = res.data?.data ?? [];
    const newRequests = all.slice(0, all.length - baselineCount);
    // Filter to only callbacks belonging to this applicationId
    const matched = applicationId
      ? newRequests.filter(cb => {
          const content = cb.content ?? cb.body ?? '';
          return typeof content === 'string' ? content.includes(applicationId) : JSON.stringify(content).includes(applicationId);
        })
      : newRequests;
    if (matched.length >= expectedCount) return matched;
    console.log(`    Polling… ${matched.length}/${expectedCount} callbacks received (${newRequests.length} total new)`);
  }
  throw new Error(`Timed out after ${timeoutMs / 1000}s waiting for ${expectedCount} callbacks`);
}

async function decryptCallback(rawBody) {
  const res = await axios.post(DECRYPT_URL, rawBody, {
    headers: {
      Authorization: `Bearer ${getIapToken()}`,
      'Content-Type': 'text/plain',
    },
    validateStatus: () => true,
  });
  if (res.status !== 200) {
    throw new Error(`Decrypt returned HTTP ${res.status}: ${JSON.stringify(res.data).slice(0, 300)}`);
  }
  return typeof res.data === 'string' ? JSON.parse(res.data) : res.data;
}

function assertField(obj, path, label) {
  try {
    const val = resolvePath(obj, path);
    if (val == null) return `${label}: ${path} is null`;
    return null;
  } catch {
    return `${label}: ${path} not found`;
  }
}

function validateDocumentCallback(decrypted) {
  const fields = [
    'applicationId', 'submissionId', 'documentId', 'publicUserId',
    'status', 'documentType', 'documentClassification',
    'ocrResult.documentData', 'ocrResult.transactions',
    'ocrResult.fraudChecks', 'ocrResult.qualityCheck',
    'ocrResult.completenessCheck',
  ];
  return fields.map(f => assertField(decrypted, f, 'doc-callback')).filter(Boolean);
}

function validateApplicationCallback(decrypted) {
  const topFields = ['applicationId', 'submissionId', 'publicUserId', 'status'];
  const bsFields = [
    'ocrResult.computedFields.BANK_STATEMENT.gs_180days_valid_bankstatement',
    'ocrResult.computedFields.BANK_STATEMENT.gs_90days_consec_bankstatement',
    'ocrResult.computedFields.BANK_STATEMENT.gs_totaldebit_bankstatement',
    'ocrResult.computedFields.BANK_STATEMENT.gs_totalcredit_bankstatement',
    'ocrResult.computedFields.BANK_STATEMENT.gs_inferredincome_bankstatement',
    'ocrResult.computedFields.crossCheckFindings',
  ];
  return [...topFields, ...bsFields]
    .map(f => assertField(decrypted, f, 'app-callback'))
    .filter(Boolean);
}

async function runBatchTestCase(tc) {
  console.log(`  Running ${tc.id} (batch) — POST /ai-gateway/batch-upload`);

  const missingBatchVars = [];
  if (!WEBHOOK_TOKEN_ID) missingBatchVars.push('WEBHOOK_TOKEN_ID');
  if (!GOOGLE_SA_KEY_FILE) missingBatchVars.push('GOOGLE_SA_KEY_FILE');
  if (missingBatchVars.length) {
    const note = `⚠️ SKIPPED — batch TC requires ${missingBatchVars.join(', ')}`;
    console.log(`  ${note}`);
    return {
      passed: false,
      actualResult: note,
      curlCmd: '(batch — env vars missing)',
      failedAssertions: null,
      skipped: true,
    };
  }

  // Inject webhook callbacks into payload if not already set
  const payload = JSON.parse(JSON.stringify(tc.payload));
  if (!payload.callbacks) {
    const webhookIapHeader = { Authorization: `Bearer ${getWebhookIapToken()}` };
    payload.callbacks = {
      documentResult: {
        url: `${WEBHOOK_SERVER_URL}/${WEBHOOK_TOKEN_ID}`,
        method: 'POST',
        headers: webhookIapHeader,
      },
      applicationResult: {
        url: `${WEBHOOK_SERVER_URL}/${WEBHOOK_TOKEN_ID}`,
        method: 'POST',
        headers: webhookIapHeader,
      },
    };
  }

  const curlCmd = [
    `curl -X POST '${PREVIEW_URL}/ai-gateway/batch-upload'`,
    `-H 'X-Tenant-Token: ${VERIFYIQ_KEY ? VERIFYIQ_KEY.slice(0, 3) + '***' : '(unset)'}'`,
    `-H 'Authorization: Bearer <IAP_TOKEN>'`,
    `-H 'Content-Type: application/json'`,
    `-d '${JSON.stringify(payload).slice(0, 500)}...'`,
  ].join(' \\\n    ');
  console.log(`  curl: ${curlCmd}`);

  // 1. Get baseline webhook count
  let baselineCount;
  try {
    baselineCount = await getWebhookBaseline();
    console.log(`    Webhook baseline: ${baselineCount} existing requests`);
  } catch (err) {
    return { passed: false, actualResult: `Webhook baseline failed: ${err.message}`, curlCmd, failedAssertions: null };
  }

  // 2. POST to batch-upload
  let status, body;
  try {
    const client = axios.create({
      baseURL: PREVIEW_URL,
      headers: {
        Authorization: `Bearer ${getIapToken()}`,
        'X-Tenant-Token': VERIFYIQ_KEY,
        'Content-Type': 'application/json',
      },
      validateStatus: () => true,
    });
    const res = await client.post('/ai-gateway/batch-upload', payload);
    status = res.status;
    body = res.data;
  } catch (err) {
    return { passed: false, actualResult: `POST error: ${err.message}`, curlCmd, failedAssertions: null };
  }

  console.log(`    POST response: HTTP ${status}`);

  if (status !== 200) {
    return {
      passed: false,
      actualResult: `Expected HTTP 200, got ${status}. Body: ${JSON.stringify(body).slice(0, 300)}`,
      curlCmd,
      failedAssertions: `Expected 200, got ${status}`,
    };
  }

  // 3. Assert initial response fields (only require applicationId — status may be ACCEPTED or FAILED)
  if (!body.applicationId) {
    return { passed: false, actualResult: 'Missing applicationId in response', curlCmd, failedAssertions: 'Missing applicationId' };
  }
  console.log(`    ✓ HTTP 200, applicationId=${body.applicationId}, status=${body.status}`);

  // 4. Poll for webhook callbacks
  const docCount = payload.payload?.documents?.length ?? 1;
  const expectedCallbacks = docCount + 1; // N document callbacks + 1 application callback
  let callbacks;
  try {
    console.log(`    Waiting for ${expectedCallbacks} callbacks (${docCount} doc + 1 app)...`);
    callbacks = await pollWebhookCallbacks(baselineCount, expectedCallbacks, body.applicationId);
    console.log(`    ✓ Received ${callbacks.length} callbacks`);
  } catch (err) {
    return { passed: false, actualResult: err.message, curlCmd, failedAssertions: `Polling: ${err.message}` };
  }

  // 5. Decrypt and validate each callback
  const allErrors = [];
  for (const cb of callbacks) {
    const rawBody = cb.content ?? cb.body ?? JSON.stringify(cb);
    let decrypted;
    try {
      decrypted = await decryptCallback(rawBody);
    } catch (err) {
      allErrors.push(`Decrypt failed: ${err.message}`);
      continue;
    }

    const isDocLevel = !!decrypted.documentId;
    if (isDocLevel) {
      const docErrors = validateDocumentCallback(decrypted);
      if (docErrors.length) allErrors.push(...docErrors);
      else console.log(`    ✓ Document callback OK (docId=${decrypted.documentId})`);
    } else {
      const appErrors = validateApplicationCallback(decrypted);
      if (appErrors.length) allErrors.push(...appErrors);
      else console.log(`    ✓ Application callback OK (appId=${decrypted.applicationId})`);
    }
  }

  if (allErrors.length) {
    return {
      passed: false,
      actualResult: `Callback validation: ${allErrors.length} error(s): ${allErrors.join('; ')}`,
      curlCmd,
      failedAssertions: allErrors.join('\n'),
    };
  }

  return { passed: true, actualResult: `HTTP 200 ACCEPTED — ${callbacks.length} callbacks validated`, curlCmd, failedAssertions: null };
}

// ── Step 5: Post results comment ──────────────────────────────────────────────

async function postResultsComment(summary, results) {
  const passed = results.filter(r => r.passed).length;
  const total  = results.length;
  const icon   = passed === total ? '✅' : passed > 0 ? '⚠️' : '❌';

  const rows = results.map(r => {
    const rowIcon = r.passed ? '✅' : '❌';
    const cu      = r.taskUrl ? `[${r.taskId}](${r.taskUrl})` : '—';
    return `| ${rowIcon} | \`${r.id}\` | ${r.type} | ${r.title} | ${r.actualResult} | ${cu} |`;
  }).join('\n');

  const now  = new Date().toISOString().replace('T', ' ').slice(0, 16) + ' UTC';
  const body = [
    `## ${icon} QA Results — ${passed}/${total} passed`,
    '',
    `**Changes analysed:** ${summary}`,
    '',
    '| | ID | Type | Test | Result | ClickUp |',
    '|---|---|---|---|---|---|',
    rows,
    '',
    `<sub>Generated by claude-code-action (QA) · ${now}</sub>`,
  ].join('\n');

  await github.post(`/repos/${PR_REPO}/issues/${PR_NUMBER}/comments`, { body });
  console.log('→ Results comment posted.');
}

// ── Main ──────────────────────────────────────────────────────────────────────

async function main() {
  const { summary, test_cases: testCases } = loadTestCases();
  console.log(`→ ${testCases.length} test cases loaded\n`);

  const pr = await getPr();
  await createClickUpList(pr);

  // Create a fresh webhook token for batch tests (only if env vars are available)
  const hasBatchTests = testCases.some(tc => tc.type === 'batch');
  const batchEnvReady = GOOGLE_SA_KEY_FILE && WEBHOOK_SERVER_URL;
  if (hasBatchTests && batchEnvReady) {
    WEBHOOK_TOKEN_ID = await createWebhookToken();
  } else if (hasBatchTests) {
    console.warn('  ⚠ Batch TCs found but GOOGLE_SA_KEY_FILE / WEBHOOK_SERVER_URL not set — batch TCs will be skipped');
  }

  const results = [];
  try {
    for (const tc of testCases) {
      // Skip TCs flagged as needing a fixture upload
      if (tc.needs_fixture) {
        const note = tc.fixture_note || 'Fixture not found in gs://qa-automation-dev — upload required';
        console.log(`  ⚠️ ${tc.id}: SKIPPED — ${note}`);

        // Create ClickUp task with "to do" status + needs-fixture tag
        let taskId = null, taskUrl = null;
        if (clickupListId) {
          try {
            const { data } = await clickup.post(`/list/${clickupListId}/task`, {
              name: `${tc.id} - ${tc.title}`,
              description: buildDescription(tc),
              tags: [tc.type, 'qa-auto', 'needs-fixture'],
              status: 'to do',
            });
            taskId = data.id;
            taskUrl = data.url;
            console.log(`  ✓ ClickUp: ${taskUrl}`);

            // Post the fixture_note as a comment
            await clickup.post(`/task/${taskId}/comment`, {
              comment_text: [
                '**Result:** ⚠️ SKIPPED — fixture not available',
                '',
                `**Note:** ${note}`,
                '',
                'Upload the required fixture to gs://qa-automation-dev/ and re-run the workflow.',
              ].join('\n'),
            });
          } catch (err) {
            console.warn(`  ⚠ ClickUp create/update failed for skipped TC ${tc.id}: ${err.message}`);
          }
        }

        results.push({
          ...tc,
          passed: false,
          actualResult: `⚠️ SKIPPED — ${note}`,
          taskId,
          taskUrl,
        });
        continue;
      }

      const { id: taskId, url: taskUrl } = await createClickUpTask(tc);
      const runner = tc.type === 'batch' ? runBatchTestCase : runTestCase;
      const { passed, actualResult, curlCmd, failedAssertions, assertionResults, responseBody } = await runner(tc);
      await updateClickUpTask(taskId, tc, actualResult, passed, curlCmd, failedAssertions, assertionResults, responseBody);

      console.log(`  ${passed ? '✅' : '❌'} ${tc.id}: ${actualResult}`);
      results.push({ ...tc, passed, actualResult, taskId, taskUrl });
    }
  } finally {
    if (hasBatchTests) {
      await deleteWebhookToken(WEBHOOK_TOKEN_ID);
    }
  }

  console.log();
  await postResultsComment(summary, results);

  const passedCount = results.filter(r => r.passed).length;
  console.log(`\n→ Done. ${passedCount}/${results.length} passed.`);
  if (passedCount < results.length) process.exit(1);
}

main().catch(err => {
  console.error('Fatal:', err.message);
  process.exit(1);
});
